service_name: machinegun
erlang:
    secret_cookie_file: "/opt/machinegun/etc/cookie"

namespaces:
    apikeymgmt:
        processor:
            url: http://token-keeper:8022/v2/stateproc
            pool_size: 300

storage:
    type: memory

woody_server:
    max_concurrent_connections: 8000
    http_keep_alive_timeout: 15S

    logging:
    out_type: stdout
    level: info

opentelemetry:
    service_name: machinegun
    exporter:
        protocol: http/protobuf
        endpoint: http://jaeger:4318
